language: ruby

services:
  - docker
env:
  global:
    - IMAGE_NAME=mstroecker/zig-robotstxt

script:
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:0.4"
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:0.4"
  on:
    branch: master
